export const BUS_FETCH_REQUEST = "BUS_FETCH_REQUEST"
export const BUS_FETCH_SUCCESS = "BUS_FETCH_SUCCESS"
export const BUS_FETCH_FAIL = "BUS_FETCH_FAIL"
export const BUS_FETCH_RESET = "BUS_FETCH_RESET"

export const BUS_ADD_REQUEST = "BUS_ADD_REQUEST"
export const BUS_ADD_SUCCESS = "BUS_ADD_SUCCESS"
export const BUS_ADD_FAIL = "BUS_ADD_FAIL"
export const BUS_ADD_RESET = "BUS_ADD_RESET"

export const BUS_CANCEL_REQUEST= "BUS_CANCEL_REQUEST"
export const BUS_CANCEL_SUCCESS= "BUS_CANCEL_SUCCESS"
export const BUS_CANCEL_FAIL= "BUS_CANCEL_FAIL"
export const BUS_CANCEL_RESET= "BUS_CANCEL_RESET"


